---
periodics:
  - name: ci-infra-prow-labelsync
    cron: "17 * * * *" # Every hour at 17 minutes past the hour
    cluster: default
    decorate: true
    labels:
      app: label-sync
    extra_refs:
    - org: kubestellar
      repo: infra
      base_ref: main
      clone_uri: "https://github.com/kubestellar/infra.git"
    spec:
      containers:
      - image: us-docker.pkg.dev/k8s-infra-prow/images/label_sync:v20240802-66b115076
        command:
        - label_sync
        args:
        - --config=/home/prow/go/src/github.com/kubestellar/infra/prow/labels.yaml
        - --confirm=true
        - --orgs=kubestellar
        - --github-app-id=1227751
        - --github-app-private-key-path=/etc/github-app/cert
        - --endpoint=http://ghproxy.prow.svc.cluster.local
        - --endpoint=https://api.github.com
        - --debug
        volumeMounts:
        - name: github-app
          mountPath: /etc/github-app
          readOnly: true
      volumes:
      - name: github-app
        secret:
          secretName: github-token
