---
periodics:
  - name: ci-infra-prow-labelsync
    cron: "17 * * * *" # Every hour at 17 minutes past the hour
    cluster: default
    decorate: true
    labels:
      app: label-sync
    extra_refs:
    - org: kubestellar
      repo: infra
      base_ref: main
      clone_uri: "https://github.com/kubestellar/infra.git"
    spec:
      containers:
      - image: us-docker.pkg.dev/k8s-infra-prow/images/label_sync:v20260109-e821f0db6
        command:
        - /bin/sh
        - -c
        - |
          # Sync repos one at a time to avoid parallel request hangs
          # Get list of public, non-archived repos dynamically
          REPOS=$(label_sync --config=/home/prow/go/src/github.com/kubestellar/infra/prow/labels.yaml --orgs=kubestellar --action=docs 2>/dev/null | grep "kubestellar/" | cut -d'/' -f2 | sort -u || echo "")

          # If we can't get repo list dynamically, use known public repos
          # Excluded: core, homebrew-kubestellar (private), ocm-transport-plugin (archived)
          if [ -z "$REPOS" ]; then
            REPOS=".github a2a community docs galaxy helm homebrew-kubectl-multi infra kubectl-multi-plugin kubectl-rbac-flatten-plugin kubeflex kubestellar kubestellar-killercoda ocm-status-addon presentations repo-template repo-template-go ui ui-plugins"
          fi

          FAILED=""
          SUCCESS_COUNT=0
          for repo in $REPOS; do
            echo "=== Syncing kubestellar/$repo ==="
            if label_sync \
              --config=/home/prow/go/src/github.com/kubestellar/infra/prow/labels.yaml \
              --confirm=true \
              --only=kubestellar/$repo \
              --github-app-id=$GITHUB_APP_ID \
              --github-app-private-key-path=/etc/github/cert \
              --github-endpoint=https://api.github.com; then
              echo "SUCCESS: kubestellar/$repo"
              SUCCESS_COUNT=$((SUCCESS_COUNT + 1))
            else
              echo "FAILED: kubestellar/$repo (may be deleted, archived, or private)"
              FAILED="$FAILED $repo"
            fi
            echo ""
          done

          echo "=== Summary ==="
          echo "Successful: $SUCCESS_COUNT repos"
          if [ -n "$FAILED" ]; then
            echo "Failed:$FAILED"
            echo "Note: Failures may be due to deleted, archived, or private repos"
          fi
          # Only fail if ALL repos failed
          if [ "$SUCCESS_COUNT" -eq 0 ]; then
            echo "ERROR: All repos failed to sync"
            exit 1
          fi
          echo "Label sync completed"
        env:
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              name: github-token
              key: appid
        volumeMounts:
        - name: github-token
          mountPath: /etc/github
          readOnly: true
      volumes:
      - name: github-token
        secret:
          secretName: github-token

  - name: ci-infra-prow-autobump
    cron: "30 3 * * 1"  # Weekly on Monday at 3:30 AM UTC
    cluster: default
    decorate: true
    labels:
      app: autobumper
    extra_refs:
    - org: kubestellar
      repo: infra
      base_ref: main
      clone_uri: "https://github.com/kubestellar/infra.git"
    spec:
      containers:
      - image: us-docker.pkg.dev/k8s-infra-prow/images/generic-autobumper:v20260109-e821f0db6
        command:
        - generic-autobumper
        args:
        - --config=/home/prow/go/src/github.com/kubestellar/infra/prow/autobump-config.yaml
        volumeMounts:
        - name: github-token
          mountPath: /etc/github-token
          readOnly: true
      volumes:
      - name: github-token
        secret:
          secretName: github-token
