---
periodics:
  - name: ci-infra-prow-labelsync
    cron: "17 * * * *" # Every hour at 17 minutes past the hour
    cluster: default
    decorate: true
    labels:
      app: label-sync
    extra_refs:
    - org: kubestellar
      repo: infra
      base_ref: main
      clone_uri: "https://github.com/kubestellar/infra.git"
    spec:
      containers:
      # Use simple --orgs flag to let label_sync discover repos
      # label_sync queries GitHub API and handles archived/deleted repos gracefully
      - image: gcr.io/k8s-prow/label_sync:v20240731-a5d9345e59
        command:
        - label_sync
        args:
        - --config=/home/prow/go/src/github.com/kubestellar/infra/prow/labels.yaml
        - --confirm=true
        - --orgs=kubestellar
        - --github-app-id=$(GITHUB_APP_ID)
        - --github-app-private-key-path=/etc/github/cert
        - --github-endpoint=https://api.github.com
        env:
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              name: github-token
              key: appid
        volumeMounts:
        - name: github-app-key
          mountPath: /etc/github
          readOnly: true
      volumes:
      - name: github-app-key
        secret:
          secretName: github-token

  - name: ci-infra-prow-autobump
    cron: "30 3 * * 1"  # Weekly on Monday at 3:30 AM UTC
    cluster: default
    decorate: true
    labels:
      app: autobumper
    extra_refs:
    - org: kubestellar
      repo: infra
      base_ref: main
      clone_uri: "https://github.com/kubestellar/infra.git"
    spec:
      containers:
      - image: us-docker.pkg.dev/k8s-infra-prow/images/generic-autobumper:v20260109-e821f0db6
        command:
        - generic-autobumper
        args:
        - --config=/home/prow/go/src/github.com/kubestellar/infra/prow/autobump-config.yaml
        volumeMounts:
        - name: github-app-key
          mountPath: /etc/github-token
          readOnly: true
      volumes:
      - name: github-app-key
        secret:
          secretName: github-token
