---
periodics:
  - name: ci-infra-prow-labelsync
    cron: "17 * * * *" # Every hour at 17 minutes past the hour
    cluster: default
    decorate: true
    labels:
      app: label-sync
    extra_refs:
    - org: kubestellar
      repo: infra
      base_ref: main
      clone_uri: "https://github.com/kubestellar/infra.git"
    spec:
      containers:
      - image: gcr.io/k8s-prow/label_sync:v20240731-a5d9345e59
        command:
        - /bin/sh
        - -c
        - |
          # Sync repos one at a time to avoid parallel request hangs
          REPOS=$(label_sync --config=/home/prow/go/src/github.com/kubestellar/infra/prow/labels.yaml --orgs=kubestellar --action=docs 2>/dev/null | grep "kubestellar/" | cut -d'/' -f2 | sort -u || echo "")

          # If we can't get repo list dynamically, use known repos
          if [ -z "$REPOS" ]; then
            REPOS=".github a2a community core docs galaxy helm homebrew-kubectl-multi homebrew-kubestellar infra kubectl-multi-plugin kubectl-rbac-flatten-plugin kubeflex kubestellar kubestellar-infrastructure kubestellar-killercoda ocm-status-addon ocm-transport-plugin presentations repo-template repo-template-go ui ui-plugins"
          fi

          FAILED=""
          for repo in $REPOS; do
            echo "=== Syncing kubestellar/$repo ==="
            if label_sync \
              --config=/home/prow/go/src/github.com/kubestellar/infra/prow/labels.yaml \
              --confirm=true \
              --only=kubestellar/$repo \
              --token=/etc/oauth/token \
              --endpoint=https://api.github.com; then
              echo "SUCCESS: kubestellar/$repo"
            else
              echo "FAILED: kubestellar/$repo"
              FAILED="$FAILED $repo"
            fi
            echo ""
          done

          if [ -n "$FAILED" ]; then
            echo "Failed repos:$FAILED"
            exit 1
          fi
          echo "All repos synced successfully"
        volumeMounts:
        - name: oauth-token
          mountPath: /etc/oauth
          readOnly: true
      volumes:
      - name: oauth-token
        secret:
          secretName: github-oauth-token
