# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
# trigger will make sure that test jobs only run on trusted PRs
triggers:
  - repos:
      - kubestellar  # Org-wide: applies to all repos in the kubestellar org
    only_org_members: true

approve:
  - repos:
      - kubestellar  # Org-wide
    ignore_review_state: true
    require_self_approval: true

lgtm:
  - repos:
      - kubestellar  # Org-wide
    # adds lgtm if GitHub review state is "Approve"
    # and removes lgtm if review state is "Request Changes"
    review_acts_as_lgtm: true
    # preserves lgtm on rebase or squash
    store_tree_hash: true

dco:
  kubestellar:  # Org-wide
    # Trust GitHub Copilot app - skip DCO check for Copilot-authored commits
    # Note: commit author is "Copilot", not "copilot-swe-agent" (which is the PR author)
    trusted_apps:
      - Copilot

# config_updater will automatically update the config configmap when config.yaml changes
config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    prow/labels.yaml:
      name: label-config
    prow/jobs/**/*.yaml:
      name: job-config
      # makes it so we can have "jobs/foo/presubmits.yaml" and "jobs/bar/presubmits.yaml"
      # without naming conflicts (by default, Prow would use just the basename)
      use_full_path_as_key: true

cherry_pick_unapproved:
  branchregexp: "^release.*$"
  comment: |
    This cherry pick PR is for a release branch and has not yet been approved by Release Managers.
    Adding the `do-not-merge/cherry-pick-not-approved` label.

    To merge this cherry pick, it must first be approved (`/lgtm` + `/approve`) by the relevant OWNERS.

label:
  additional_labels:
    - "blocked by backend"
    - "merge-type/merge"
    - "merge-type/squash"
    - "merge-type/rebase"
    - "needs details"
    - "service accounts"
    - Epic
    - design
    - feature
    - proposal
    - ready-to-challenge
    - redesign

plugins:
  # Org-wide defaults - applies to ALL repos in kubestellar org
  kubestellar:
    plugins:
      - approve
      - assign
      - branchcleaner
      - dco
      - hold
      - label
      - lgtm
      - lifecycle
      - milestoneapplier
      - override
      - owners-label
      - retitle
      - size
      - skip
      - trigger
      - verify-owners
      - wip

  # Repo-specific overrides (only for repos needing additional plugins)
  kubestellar/infra:
    plugins:
      - config-updater  # Only infra needs config-updater for prow config sync

require_matching_label:
  - missing_label: do-not-merge/needs-kind
    org: kubestellar
    repo: kubestellar
    prs: true
    regexp: ^kind/
  - missing_label: needs-triage
    org: kubestellar
    issues: true
    regexp: ^triage/

external_plugins:
  # Org-wide external plugins
  kubestellar:
    - name: needs-rebase
      events:
        - pull_request
    - name: cherrypicker
      events:
        - issue_comment
        - pull_request

owners:
  filenames:
    kubestellar/controller-runtime:
      owners: DOWNSTREAM_OWNERS
      owners_aliases: DOWNSTREAM_OWNERS_ALIASES
