name: Reusable PR Title Verifier

on:
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: PR title check removed
        run: echo "PR title emoji check has been removed."
